version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        environment:
            - NODE_ENV=production
            - PORT=3001
        networks:
            - app-network

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NUXT_PUBLIC_API_BASE=http://localhost:3001
            - NODE_ENV=production
        depends_on:
            - backend
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
